/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package catalogoInmuebles.interfaz;

import catalogoInmuebles.mundo.GestionBD;
import catalogoInmuebles.mundo.Inmueble;
import com.j256.ormlite.jdbc.JdbcConnectionSource;
import com.j256.ormlite.support.ConnectionSource;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Andrea Baron
 */

/**
 * Frame principal del Catálogo de Inmuebles.
 */
public class FrameCatalogoInmuebles extends javax.swing.JFrame {

    private GestionBD gestionbd = new GestionBD();
    private List<Inmueble> listaResultados = new ArrayList<>();

    /**
     * Creates new form FrameCatalogoInmuebles
     */
    public FrameCatalogoInmuebles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        lblCarpeta_img = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMayorPrecio = new javax.swing.JButton();
        btnMenorPrecio = new javax.swing.JButton();
        btnMayorArea = new javax.swing.JButton();
        btnMenorArea = new javax.swing.JButton();
        btnPorCodigo = new javax.swing.JButton();
        lblBuscar_img = new javax.swing.JLabel();
        btnLocalidad = new javax.swing.JButton();
        btnPrecio = new javax.swing.JButton();
        btnTipoInmueble = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catálogo de Inmuebles - Bienvenida");
        setName("frmPrincipal"); // NOI18N
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Inmuebles"));
        jPanel3.setToolTipText("");
        jPanel3.setName("pnl_Inmuebles"); // NOI18N

        btnIngresar.setMnemonic('I');
        btnIngresar.setText("Ingresar Inmueble");
        btnIngresar.setToolTipText("Permite ingresar un nuevo inmueble.");
        btnIngresar.setName("btnIngresar"); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblCarpeta_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalogoInmuebles/interfaz/img/carpeta.png"))); // NOI18N
        lblCarpeta_img.setName("imgInmueble"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblCarpeta_img)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCarpeta_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de búsqueda"));
        jPanel4.setToolTipText("");
        jPanel4.setName("pnlBusqueda"); // NOI18N

        btnMayorPrecio.setMnemonic('m');
        btnMayorPrecio.setText("Mayor precio");
        btnMayorPrecio.setToolTipText("Muestra el inmueble más caro.");
        btnMayorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnMayorPrecioActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnMenorPrecio.setMnemonic('e');
        btnMenorPrecio.setText("Menor precio");
        btnMenorPrecio.setToolTipText("Muestra el inmueble más barato.");
        btnMenorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnMenorPrecioActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnMayorArea.setMnemonic('a');
        btnMayorArea.setText("Mayor área");
        btnMayorArea.setToolTipText("Muestra el inmueble con mayor área.");
        btnMayorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnMayorAreaActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnMenorArea.setMnemonic('r');
        btnMenorArea.setText("Menor área");
        btnMenorArea.setToolTipText("Muestra el inmueble con menor área.");
        btnMenorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnMenorAreaActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnPorCodigo.setMnemonic('c');
        btnPorCodigo.setText("Código");
        btnPorCodigo.setToolTipText("Busca inmueble por código.");
        btnPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnPorCodigoActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        lblBuscar_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalogoInmuebles/interfaz/img/buscar.png"))); // NOI18N
        lblBuscar_img.setName("imgBusqueda"); // NOI18N

        btnLocalidad.setMnemonic('l');
        btnLocalidad.setText("Localidad");
        btnLocalidad.setToolTipText("Busca inmueble por localidad.");
        btnLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnLocalidadActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnPrecio.setMnemonic('p');
        btnPrecio.setText("Precio");
        btnPrecio.setToolTipText("");
        btnPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnPrecioActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btnTipoInmueble.setMnemonic('p');
        btnTipoInmueble.setText("Tipo");
        btnTipoInmueble.setToolTipText("Muestra los inmuebles que coincidan con el tipo seleccionado.");
        btnTipoInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnTipoInmuebleActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMenorPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMayorPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnMenorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnMayorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblBuscar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMayorPrecio)
                    .addComponent(btnMayorArea)
                    .addComponent(btnPorCodigo)
                    .addComponent(btnPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenorPrecio)
                    .addComponent(btnLocalidad)
                    .addComponent(btnMenorArea)
                    .addComponent(btnTipoInmueble))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Catálogo de Inmuebles");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalogoInmuebles/interfaz/img/edificios.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalogoInmuebles/interfaz/img/edificios.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        FrameIngresarInmueble frame = new FrameIngresarInmueble();
        frame.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnMayorPrecioActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnMayorPrecioActionPerformed
        listaResultados = gestionbd.buscarPorMayorPrecio();
        FrameResultados frame = new FrameResultados();
        frame.presentarTabla(listaResultados);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMayorPrecioActionPerformed

    private void btnMenorPrecioActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnMenorPrecioActionPerformed
        listaResultados = gestionbd.buscarPorMenorPrecio();
        FrameResultados frame = new FrameResultados();
        frame.presentarTabla(listaResultados);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMenorPrecioActionPerformed

    private void btnMayorAreaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnMayorAreaActionPerformed
        listaResultados = gestionbd.buscarPorMayorArea();
        FrameResultados frame = new FrameResultados();
        frame.presentarTabla(listaResultados);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMayorAreaActionPerformed

    private void btnMenorAreaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnMenorAreaActionPerformed
        listaResultados = gestionbd.buscarPorMenorArea();
        FrameResultados frame = new FrameResultados();
        frame.presentarTabla(listaResultados);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMenorAreaActionPerformed

    private void btnPorCodigoActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnPorCodigoActionPerformed
        /**
         * Activa un showInputDialog que permite ingresar el código del inmueble a buscar
         * Se envía la variable texto como parámetro al método de búsqueda. 
         */
        String texto = JOptionPane.showInputDialog("Por favor ingrese el código del inmueble:");
        if(texto.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresó ningún código.");
        }
        else {
            listaResultados = gestionbd.buscarporCodigo(texto);
            if (listaResultados.get(0) == null){
                JOptionPane.showMessageDialog(this, "El código no existe.");
            }
            else {
                FrameResultados frame = new FrameResultados();
                frame.presentarTabla(listaResultados);
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnPorCodigoActionPerformed

    private void btnLocalidadActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnLocalidadActionPerformed
        /**
         * Activa un showInputDialog que permite seleccionar una localidad, se envía "opcion" 
         * con la localidad seleccionada como parámetro al método de búsqueda. 
         */
        Object [] localidades = {"Antonio Nariño", "Barrios Unidos", "Bosa", "Chapinero", 
            "Ciudad Bolívar", "Engativá", "Fontibón", "Kennedy", "La Candelaria", 
            "Los Mártires", "Puente Aranda", "Rafael Uribe Uribe", "San Cristóbal", 
            "Santa Fe", "Suba", "Sumapaz", "Teusaquillo", "Tunjuelito", "Usaquén", "Usme"};
        Object opcion = JOptionPane.showInputDialog(null, "Seleccione una localidad:", 
                "Buscar por localidad", JOptionPane.QUESTION_MESSAGE, null, localidades, 
                DISPOSE_ON_CLOSE);
        if(opcion == null){
            JOptionPane.showMessageDialog(this, "No seleccionó ninguna localidad.");
        }
        else {
            listaResultados = gestionbd.buscarporLocalidad(opcion.toString());
            if (listaResultados.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay inmuebles disponibles en la localidad de " + opcion.toString());
            }
            else {
                FrameResultados frame = new FrameResultados();
                frame.presentarTabla(listaResultados);
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnLocalidadActionPerformed

    private void btnPrecioActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnPrecioActionPerformed
        Object [] rPrecio = {" < 1'000.000", "1'000.001 y 3'000.000", "3'000.001 y 5'000.000", " > 5'000.000"};
        Object opcion = JOptionPane.showInputDialog(null, "Seleccione el rango de precios del inmueble:",
                "Buscar por rango de precios", JOptionPane.QUESTION_MESSAGE, null, rPrecio,
                DISPOSE_ON_CLOSE);
        listaResultados = gestionbd.buscarPorPrecio(opcion.toString());
        if (listaResultados.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay inmuebles disponibles en este rango de precios: " + opcion.toString());
        }
        else {
             FrameResultados frame = new FrameResultados();
             frame.presentarTabla(listaResultados);
             frame.setVisible(true);
            }
    }//GEN-LAST:event_btnPrecioActionPerformed

    private void btnTipoInmuebleActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnTipoInmuebleActionPerformed
        /**
         * Activa un showInputDialog que permite seleccionar el Tipo de Inmueble, se envía 
         * el objeto opcion con el tipo seleccionado como parámetro al método de búsqueda.
         */
        Object [] tipo = {"Apartamento", "Bodega", "Casa"};
        Object opcion = JOptionPane.showInputDialog(null, "Seleccione un tipo de inmueble:", 
                "Buscar por tipo de inmueble", JOptionPane.QUESTION_MESSAGE, null, tipo, 
                DISPOSE_ON_CLOSE);
        if(opcion == null){
            JOptionPane.showMessageDialog(this, "No seleccionó ningún tipo de inmueble.");
        }
        else {
            listaResultados = gestionbd.buscarPorTipo(opcion.toString());
            if (listaResultados.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay inmuebles disponibles en el tipo de inmueble " + opcion.toString());
            }
            else {
                FrameResultados frame = new FrameResultados();
                frame.presentarTabla(listaResultados);
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnTipoInmuebleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCatalogoInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCatalogoInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCatalogoInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCatalogoInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCatalogoInmuebles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLocalidad;
    private javax.swing.JButton btnMayorArea;
    private javax.swing.JButton btnMayorPrecio;
    private javax.swing.JButton btnMenorArea;
    private javax.swing.JButton btnMenorPrecio;
    private javax.swing.JButton btnPorCodigo;
    private javax.swing.JButton btnPrecio;
    private javax.swing.JButton btnTipoInmueble;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBuscar_img;
    private javax.swing.JLabel lblCarpeta_img;
    // End of variables declaration//GEN-END:variables
}
